[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_staking = "FNpNiKrtdwhMqCtzXrU9CnsH8EuQL5LMv2pskcagVDiT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/xeony/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
